### ISSUE TITLE
Where is the result??

### ISSUE THREAD

**Issue by HIN0209** [JenifferWuUCLA/pulmonary-nodules-MaskRCNN#1]
Hello,
I am interested in the application of Mask-RCNN to medical images. But because you copied many outside codes, it is little confusing what is your original. Where is the result of detection of pulmonary nodules??

**Comment by JenifferWuUCLA** [comment]
Hello,
        Mask R-CNN lung nodule intelligence testing project is just entered the research and development stage. I am currently working on Mask-RCNN which is in the field of intelligent diagnosis of medical images, so there is a lot of external codes. I'm thinking about the Mask R-CNN TensorFlow implementation and for now I will place my debug code under the path "pulmonary-nodules-MaskRCNN / tree / master / pulmonary-nodules-Demos".
